"""initial migration.

Revision ID: 667dd5ce7981
Revises: 
Create Date: 2025-01-18 13:29:46.558448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667dd5ce7981'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
